apiVersion: v1
kind: ConfigMap
metadata:
  name: car-rental-config
data:
  ASPNETCORE_URLS: "http://+:8080"
  Jwt__Issuer: "CarRental.Api"
  Jwt__Audience: "CarRental.Client"
  Jwt__LifetimeMinutes: "60"
  InitialAdministrator__Username: "admin"
  InitialAdministrator__BirthDate: "1990-01-01"
